### ISSUE TITLE
How does this compare to other actions like https://github.com/trmcnvn/firefox-addon

### ISSUE THREAD

**Issue by djahandarie** [cardinalby/webext-buildtools-firefox-addons-action#10]
I'm currently designing a GitHub Actions CD for a Firefox extension, and I'm comparing options.

https://github.com/trmcnvn/firefox-addon seems like
* it has more stars
* it has more contributors
* it is older (and perhaps slightly abandoned?)

Given that webext-buildtools-firefox-addons-action is newer, are there any notable improvements over that action? It might be nice to include in the README here if there are

**Comment by cardinalby** [comment]
Hi! Key differences are:

- Uses Addons API v5.
- Allows uploading sources for review.
- Has detailed error outputs.
- Extracts manifest from zip archive automatically.
- Separates upload, polling for it to be ready and creating a version
- Doesn't support publishing a new add-on, only updating existing
