### ISSUE TITLE
How to attach the source zip

### ISSUE THREAD

**Issue by SettingDust** [cardinalby/webext-buildtools-firefox-addons-action#4]
Firefox need the source when code is compiled. How to upload it with action?

**Comment by cardinalby** [comment]
@SettingDust

Hi! Thank you for being interested in the project.

I looked through Signing API [documentation](https://addons-server.readthedocs.io/en/latest/topics/api/signing.html#upload-version) that is used by the action to upload a new version and didn't find any possibilities for uploading sources. 

Do you have any ideas how it can be implemented?

EDITED: I found an [announcement](https://blog.mozilla.org/addons/2022/03/17/new-api-for-submitting-and-updating-add-ons/) that says that it's possible to add sources to your add-on.

**Comment by cardinalby** [comment]
I have added new `sourcesZipFilePath` input. Please test and let me know whether it works as expected.

**Comment by SettingDust** [comment]
I've wrote by myself xdddd. https://github.com/SettingDust/publish-firefox-addon-action

The upload not in Signing part in document. 
https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-sources
