### ISSUE TITLE
Error: Submission failed: Status 400: Duplicate add-on ID found.

### ISSUE THREAD

**Issue by dominoma** [cardinalby/webext-buildtools-firefox-addons-action#5]
When using this action, deployment fails because the add-on ID already is in use. It seems that this action does not try to push an update to Firefox AMO but wants to deploy a new extension.

**Comment by cardinalby** [comment]
Hi! Thanks for reporting. 
The action uses `PUT /api/v5/addons/(string:guid)/versions/(string:version)/` [endpoint](https://addons-server.readthedocs.io/en/latest/topics/api/signing.html#put--api-v5-addons-(string-guid)-versions-(string-version)-) that uploads a new version of an existing add-on.
Can it be that you try to upload the version that is already uploaded (check the version in your manifest.json file)? 

If it still doesn't work, the following information can help me to figure out what happens:
1. yml code that calls the action (to check the inputs)
2. values of the action outputs in the workflow
3. does manual uploading work?

**Comment by cardinalby** [comment]
@dominoma Please try to check this case with the new version of the action and let me know if it was also fixed
